repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: "Format with black"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        name: "Format with prettier"
        types: [yaml, json, markdown]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
      - id: python-bandit-vulnerability-check
        name: Check for Python code vulnerabilities
        args: [-l, --recursive, -x, tests]
        files: .py$
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: Remove unused imports and unused variables
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
          ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: "Sort module imports"
        args: ["--profile", "black", "--filter-files"]
